-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 13:46:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Available Times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Available Times` (
  `Available_Time_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Tutor_ID` INT(11) NOT NULL,
  `Day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
  `Start_time` TIME NOT NULL,
  `End_Time` TIME NOT NULL,
  `Is_Free` TINYINT(4) NOT NULL,
  PRIMARY KEY (`Available_Time_ID`),
  INDEX `fk_Available Times_Tutors1_idx` (`Tutor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Available Times_Tutors1`
    FOREIGN KEY (`Tutor_ID`)
    REFERENCES `mydb`.`tutors` (`Tutor_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Classes` (
  `Class_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Tutor_ID` INT(11) NOT NULL,
  `Student_ID` INT(11) NOT NULL,
  `Date` DATE NOT NULL,
  `Start_at` TIME NOT NULL,
  `End_at` TIME NOT NULL,
  `Place` VARCHAR(225) NOT NULL,
  `Subject` VARCHAR(225) NOT NULL,
  `Price` FLOAT NOT NULL,
  PRIMARY KEY (`Class_ID`),
  INDEX `fk_Classes_Students_idx` (`Student_ID` ASC) VISIBLE,
  INDEX `fk_Classes_Tutors1_idx` (`Tutor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Classes_Students`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `mydb`.`students` (`Student_ID`),
  CONSTRAINT `fk_Classes_Tutors1`
    FOREIGN KEY (`Tutor_ID`)
    REFERENCES `mydb`.`tutors` (`Tutor_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `Review_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Tutor_ID` INT(11) NOT NULL,
  `Student_ID` INT(11) NOT NULL,
  `Rating` FLOAT NOT NULL,
  `Date` DATE NOT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Is_Tutor` TINYINT(4) NOT NULL,
  PRIMARY KEY (`Review_ID`),
  INDEX `fk_Reviews_Students1_idx` (`Student_ID` ASC) VISIBLE,
  INDEX `fk_Reviews_Tutors1_idx` (`Tutor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_Students1`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `mydb`.`students` (`Student_ID`),
  CONSTRAINT `fk_Reviews_Tutors1`
    FOREIGN KEY (`Tutor_ID`)
    REFERENCES `mydb`.`tutors` (`Tutor_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `Service_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Tutor_ID` INT(11) NOT NULL,
  `Subject_ID` INT(11) NOT NULL,
  `Service_Level` ENUM('Elementary', 'High School', 'University', 'On Demand') NOT NULL,
  `Service_Cost` INT(11) NOT NULL,
  PRIMARY KEY (`Service_ID`),
  INDEX `fk_Services_Tutors1_idx` (`Tutor_ID` ASC) VISIBLE,
  INDEX `Services_ID1_idx` (`Subject_ID` ASC) VISIBLE,
  CONSTRAINT `Services_ID1`
    FOREIGN KEY (`Subject_ID`)
    REFERENCES `mydb`.`subjects` (`Subject_ID`),
  CONSTRAINT `fk_Services_Tutors1`
    FOREIGN KEY (`Tutor_ID`)
    REFERENCES `mydb`.`tutors` (`Tutor_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `Student_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(225) NOT NULL,
  `Last_Name` VARCHAR(225) NOT NULL,
  `Date_Of_Birth` DATE NOT NULL,
  `Address` VARCHAR(225) NOT NULL,
  `Town` VARCHAR(225) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(225) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Student_ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subjects` (
  `Subject_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`Subject_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Tutor Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tutor Subjects` (
  `Tutor_Subjects_ID` INT(11) NOT NULL,
  `Subject_ID` INT(11) NOT NULL,
  `Tutor_ID` INT(11) NOT NULL,
  `Service_Level` ENUM('Elementary', 'High School', 'University', 'On Demand') NOT NULL,
  `Service_Cost` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Tutor_Subjects_ID`),
  INDEX `fk_Tutor Subjects_Subjects1_idx` (`Subject_ID` ASC) VISIBLE,
  INDEX `fk_Tutor Subjects_Tutors1_idx` (`Tutor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Tutor Subjects_Subjects1`
    FOREIGN KEY (`Subject_ID`)
    REFERENCES `mydb`.`subjects` (`Subject_ID`),
  CONSTRAINT `fk_Tutor Subjects_Tutors1`
    FOREIGN KEY (`Tutor_ID`)
    REFERENCES `mydb`.`tutors` (`Tutor_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tutors` (
  `Tutor_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(255) NOT NULL,
  `Last_Name` VARCHAR(225) NOT NULL,
  `Date_Of_Birth` DATE NOT NULL,
  `Address` VARCHAR(225) NOT NULL,
  `Town` VARCHAR(225) NOT NULL,
  `Phone_Number` VARCHAR(45) NOT NULL,
  `Availability` ENUM('fixed', 'flexible') NOT NULL,
  `Experience` TEXT NOT NULL,
  `Other_Info` TEXT NULL DEFAULT NULL,
  `Email` VARCHAR(225) NOT NULL,
  `Password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Tutor_ID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
